version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "chis-bot"
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./prod_logs:/bot/logs
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "database"
  database:
    image: "postgres:9.6.2"
    container_name: "postgres"
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
