version: "3.7"
services:
  bot-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bot/scripts/docker-dev-entrypoint.sh
    container_name: "chis-bot-dev"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./prod_logs:/bot/logs
      - ./:/bot
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    depends_on:
      - "database"
  database:
    image: "postgres:9.6.2"
    container_name: "postgres"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./scripts/postgres:/docker-entrypoint-initdb.d
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgweb:
    container_name: pgweb
    restart: unless-stopped
    image: sosedoff/pgweb
    ports:
      - "5433:8081"
    links:
      - database:postgres
    env_file:
      - .env
    depends_on:
      - database
