version: "3.7"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "chis-bot"
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "database"
  database:
    image: "postgres:alpine"
    container_name: "postgres"
    env_file:
      - .env.prod
    # volumes:
    #   - ./data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
